name = "RobustNMF"
uuid = "1111f9d5-2e4d-4d00-9d07-6eab5e3037e7"
authors = ["Haitham Samaan <h.samaan@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
LinearAlgebra = "1.11.0"
Random = "1.11.0"
Statistics = "1.11.1"
julia = "1.11"
